export { Hero } from './hero'
export { Genres } from './genres'
export { Drama } from './drama'
export { Fantastic } from './fantastic'
export { Info } from './info'
export { Comedy } from './comedy'
export { ForFamily } from './for-family'
export { Action } from './action'
